### ISSUE TITLE
Typo in install command

### ISSUE THREAD

**Issue by albacoretuna** [arei/license-extractor#2]
The install command in npmjs page has a typo, even though the readme on github is ok: 
```
npm install licesne-extractor
```

Besides I couldn't get this working, is it a command line tool?

**Comment by Eeems** [comment]
Looks like the typo was fixed in #1 but not published.

**Comment by arei** [comment]
LGTM. 
![image](https://user-images.githubusercontent.com/1062655/152997731-bc215012-27c1-4048-ad0e-b23b776d36ce.png)
